name: Commit automated updates

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the triggering branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Commit and push automated updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply automated updates"
          branch: ${{ github.head_ref || github.ref_name }}